In [29]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

In [30]:

steps = [
    ("standard_scaler", StandardScaler()),
    ("classifier", LogisticRegression())
]


In [31]:
steps
[('standard_scaler', StandardScaler()), ('classifier',
LogisticRegression())]

[('standard_scaler', StandardScaler()), ('classifier', LogisticRegression())]

In [32]:
pipe=Pipeline(steps)


In [33]:
from sklearn import set_config
set_config(display="diagram")


In [34]:
pipe


Pipeline(steps=[('standard_scaler', StandardScaler()),
                ('classifier', LogisticRegression())])

In [35]:
from sklearn.datasets import make_classification
X,y=make_classification(n_samples=1000)

In [36]:
X.shape

(1000, 20)

In [37]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
X, y, test_size=0.33, random_state=42)

In [38]:
X_train

array([[ 0.01728509, -1.05309587,  0.14742676, ..., -0.60052112,
        -0.0317785 , -0.78568344],
       [-0.57103915,  0.55063224, -0.56271479, ...,  1.15030697,
         0.45936995,  0.91958725],
       [-0.54697418,  0.2752745 ,  0.51771002, ...,  0.69205955,
        -0.84923274, -0.2535002 ],
       ...,
       [-0.39148344, -0.40743065, -1.39645586, ..., -1.84141186,
         0.13384557, -1.77685594],
       [-1.26316502, -0.55571966,  0.11679904, ...,  1.605355  ,
        -0.72152428, -1.24179299],
       [-0.08388544,  0.18808864,  0.96854031, ...,  1.67463771,
         0.04081199,  1.63192366]])

In [39]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('standard_scaler', StandardScaler()),
                ('classifier', LogisticRegression())])

In [40]:
y_pred=pipe.predict(X_test)

In [41]:
y_pred

array([1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0,

In [42]:
from sklearn.decomposition import PCA
from sklearn.svm import SVC

In [43]:
steps=[("scaling",StandardScaler()),
      ("PCA",PCA(n_components=3)),
      ("SVC",SVC())]

In [44]:
pipe2=Pipeline(steps)


In [45]:
pipe2.fit(X_train,y_train)

Pipeline(steps=[('scaling', StandardScaler()), ('PCA', PCA(n_components=3)),
                ('SVC', SVC())])

In [46]:
Pipeline(steps=[('scaling', StandardScaler()), ('PCA',
PCA(n_components=3)),
 ('SVC', SVC())])

Pipeline(steps=[('scaling', StandardScaler()), ('PCA', PCA(n_components=3)),
                ('SVC', SVC())])

In [47]:
pipe2.predict(X_test)

array([1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,

In [48]:
from sklearn.impute import SimpleImputer

In [50]:
numeric_processor = Pipeline(
    steps=[
        ("imputation_mean", SimpleImputer(missing_values=np.nan, strategy="mean")),
        ("scaler", StandardScaler())
    ]
)


In [51]:
numeric_processor


Pipeline(steps=[('imputation_mean', SimpleImputer()),
                ('scaler', StandardScaler())])

In [54]:
from sklearn.preprocessing import OneHotEncoder
categorical_processor = Pipeline(
    steps=[("imputation_constant", SimpleImputer(fill_value="missing", strategy="constant")),
        ("onehot", OneHotEncoder(handle_unknown="ignore"))
    ]
)



In [56]:
categorical_processor = Pipeline(
    steps=[
        ('imputation_constant', SimpleImputer(fill_value='missing', strategy='constant')),
        ('onehot', OneHotEncoder(handle_unknown='ignore'))
    ]
)


In [57]:
from sklearn.compose import ColumnTransformer

In [59]:
preprocessor=ColumnTransformer(
    [("categorical",categorical_processor,["gender","City"]),
      ("numerical",numeric_processor,["age","height"])]
    )
     
    

<class 'SyntaxError'>: incomplete input (<ipython-input-62-4625bc511286>, line 5)